### PR TITLE
(#1180) Warn if $CC is not set up

### LINKED ISSUE #1180: Vague error message in ./build_posix.sh when $CC environment variable is not set
## Script output:
```sh
+ pkg-config --cflags sdl2
+ CFLAGS= -Wall -Wextra -Wconversion -Wunused -Wunused-function -Wunused-label -Wunused-macros -Wunused-parameter -Wunused-value -Wunused-variable -Wcast-align -Wcast-qual -Wmissing-declarations -Wredundant-decls -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch -Wmissing-field-initializers -fno-common -fno-strict-aliasing -pedantic -std=c11 -ggdb -O3 -D_REENTRANT -I/usr/include/SDL2 -I./src/
+ [ ! -z  ]
+ pkg-config --libs sdl2
+ LIBS= -lSDL2 -lm
+ -Wall -Wextra -Wconversion -Wunused -Wunused-function -Wunused-label -Wunused-macros -Wunused-parameter -Wunused-value -Wunused-variable -Wcast-align -Wcast-qual -Wmissing-declarations -Wredundant-decls -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wshadow -Wstrict-prototypes -Wwrite-strings -Wswitch -Wmissing-field-initializers -fno-common -fno-strict-aliasing -pedantic -std=c11 -ggdb -O3 -D_REENTRANT -I/usr/include/SDL2 -I./src/ -o nothing nothing.c -lSDL2 -lm
./build-posix.sh: 13: -Wall: not found
```

## Steps to reproduce:
```sh
CC=               #if your CC has path to the compiler
./build-posix.sh  #run the script
```

### PR DESCRIPTION
**Pull request by gooddoog**
This PR is going to resolve #1180

### CODE REVIEW

File: build-posix.sh [hunk 1]
```diff
@@ -10,4 +10,9 @@ fi
 
 LIBS="$LIBS $(pkg-config --libs sdl2) -lm"
 
+if [ ${#CC} -eq "0" ]; then
+    echo "CC variable is not set up!"
+    return
```
Comment (rexim) [inline build-posix.sh]: But will that actually fail the whole build? Maybe something like `exit 1` would be better?

Comment (gooddoog) [reply build-posix.sh]: It will actually, but I agree, `exit 1` is better

**Comment by rexim** [comment]
@gooddoog looks good to me! :+1: Thank you very much for the contribution!
