### PR TITLE
(#1185) Change level file save destination

### LINKED ISSUE #1185: Level editor doesn't save file to assets dir
### Steps to reproduce ###
1. Start game
1. Press `N`, `Tab`, `S`
1. Type level name
1. Press `Enter`
1. Restart game
### Observed ###
No new level, because level file appears in folder along with Nothing binary.
### Expected ###
Level file created in assets/levels folder and on the next game start it shows in level picker.

### PR DESCRIPTION
**Pull request by kolumb**
Close #1185.
I tried to combine string_duplicate and string_append but failed. Again buffers..

### CODE REVIEW

File: src/game/level/level_editor.c [hunk 1]
```diff
@@ -388,12 +389,15 @@ int level_editor_saveas_event(LevelEditor *level_editor,
...
+                LEVEL_FOLDER_MAX_LENGTH,
+                "./assets/levels//%s.txt",
+                edit_field_as_text(level_editor->edit_field_filename));
             level_editor->file_name = PUSH_LT(
                 level_editor->lt,
-                string_duplicate(
-                    edit_field_as_text(
-                        level_editor->edit_field_filename),
-                    NULL),
+                path,
```
Comment (rexim) [inline src/game/level/level_editor.c]: Are you seriously pushing a string allocated on the stack to a Lifetime object? That's a pretty reliable way to corrupt your stack. Please, at least duplicate it or something.

**Comment by rexim** [comment]
@kolumb looks good to me! :+1: Thank you for the contribution!
